library(Synth)
library(plyr)
library(compiler)
library(dplyr)
library(kohonen)
path<- 'https://raw.githubusercontent.com/liyujiao1026/ikea_0312/master/'
data_firm <- read.csv(paste0(path, 'IKEA_data_0312.csv'))
data_firm$Kommun_name <- as.character(data_firm$Kommun_name)

source(paste0(path,'1_Func_SCM.R'), echo = F)
source(paste0(path,'2_Func_cluster.R'), echo = F)
source(paste0(path,'3_Func_bootstrapSCM.R'), echo = F)
source(paste0(path,'4_Func_parametric.R'), echo = F)
source(paste0(path,'5_Func_paper.R'), echo = F)
source(paste0(path,'6_Func_paper_plot.R'), echo = F)
